name: CI

on: [pull_request, push]

jobs:
  prepare_jobs:
    name: 'Prepare: job optimization'
    runs-on: ubuntu-latest
    outputs:
      pr_found: ${{ steps.pr.outputs.pr_found }}
    steps:
      - name: Get current PR
        id: pr
        uses: 8BitJonny/gh-get-current-pr@2.2.0
        with:
          filterOutClosed: true
          sha: ${{ github.event.pull_request.head.sha }}
  build:
    needs: prepare_jobs
    if: needs.prepare_jobs.outputs.pr_found == 'false' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17' ]
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload code coverage
        uses: codecov/codecov-action@v4.0.0-beta.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Release
        if: startsWith(github.ref, 'refs/tags/') && matrix.java == 11
        env:
          GPG_KEY_NAME: B70E1EAC
          GPG_PASSPHRASE_KEY: ${{ secrets.GPG_PASSPHRASE_KEY }}
          GPG_PASSPHRASE_FILE: ${{ secrets.GPG_PASSPHRASE_FILE }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        run: |
          ./ci/before-deploy.sh
          cp ./ci/.m2.settings.xml $HOME/.m2/settings.xml
          mvn deploy -P release -DskipTests=true
