name: CI

on: [create, pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17' ]
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload code coverage
        uses: codecov/codecov-action@v4.0.0-beta.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Release
        if: startsWith(github.ref, 'refs/tags/') && matrix.java == 11
        env:
          GPG_KEY_NAME: B70E1EAC
          GPG_PASSPHRASE_KEY: ${{ secrets.GPG_PASSPHRASE_KEY }}
          GPG_PASSPHRASE_FILE: ${{ secrets.GPG_PASSPHRASE_FILE }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        run: |
          ./ci/before-deploy.sh
          cp ./ci/.m2.settings.xml $HOME/.m2/settings.xml
          mvn deploy -P release -DskipTests=true
